- name: 'Install packages'
  yum:
    name: "{{ item }}"
    state: latest
  become: yes
  loop:
    - httpd
    - wget
    - git

- name: 'Copy Files to Server'
  copy:
    src: './webpage/'
    dest: '/var/www/html/'
    remote_src: no
  become: yes
  notify:
    - restart apache